// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: protos-repo/droidguard.proto
package org.microg.gms.droidguard;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;

public final class SignedDGResponse extends Message {

  public static final ByteString DEFAULT_DATA = ByteString.EMPTY;
  public static final ByteString DEFAULT_SIG = ByteString.EMPTY;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString data;

  @ProtoField(tag = 2, type = BYTES)
  public final ByteString sig;

  public SignedDGResponse(ByteString data, ByteString sig) {
    this.data = data;
    this.sig = sig;
  }

  private SignedDGResponse(Builder builder) {
    this(builder.data, builder.sig);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SignedDGResponse)) return false;
    SignedDGResponse o = (SignedDGResponse) other;
    return equals(data, o.data)
        && equals(sig, o.sig);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = data != null ? data.hashCode() : 0;
      result = result * 37 + (sig != null ? sig.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<SignedDGResponse> {

    public ByteString data;
    public ByteString sig;

    public Builder() {
    }

    public Builder(SignedDGResponse message) {
      super(message);
      if (message == null) return;
      this.data = message.data;
      this.sig = message.sig;
    }

    public Builder data(ByteString data) {
      this.data = data;
      return this;
    }

    public Builder sig(ByteString sig) {
      this.sig = sig;
      return this;
    }

    @Override
    public SignedDGResponse build() {
      return new SignedDGResponse(this);
    }
  }
}
