// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: protos-repo/droidguard.proto
package org.microg.gms.droidguard;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REPEATED;

public final class DGRequest extends Message {

  public static final List<KeyValuePair> DEFAULT_INFO = Collections.emptyList();
  public static final String DEFAULT_VERSIONNAMEPREFIX = "";
  public static final Boolean DEFAULT_HASACCOUNT = false;
  public static final Boolean DEFAULT_ISGOOGLECN = false;
  public static final Boolean DEFAULT_ENABLEINLINEVM = false;
  public static final List<ByteString> DEFAULT_CACHED = Collections.emptyList();
  public static final Integer DEFAULT_CURRENTVERSION = 0;
  public static final String DEFAULT_ARCH = "";

  @ProtoField(tag = 1)
  public final DGUsage usage;

  @ProtoField(tag = 2, label = REPEATED, messageType = KeyValuePair.class)
  public final List<KeyValuePair> info;

  @ProtoField(tag = 3, type = STRING)
  public final String versionNamePrefix;

  @ProtoField(tag = 6, type = BOOL)
  public final Boolean hasAccount;

  @ProtoField(tag = 7, type = BOOL)
  public final Boolean isGoogleCn;

  @ProtoField(tag = 8, type = BOOL)
  public final Boolean enableInlineVm;

  @ProtoField(tag = 9, type = BYTES, label = REPEATED)
  public final List<ByteString> cached;

  @ProtoField(tag = 13, type = INT32)
  public final Integer currentVersion;

  @ProtoField(tag = 14, type = STRING)
  public final String arch;

  public DGRequest(DGUsage usage, List<KeyValuePair> info, String versionNamePrefix, Boolean hasAccount, Boolean isGoogleCn, Boolean enableInlineVm, List<ByteString> cached, Integer currentVersion, String arch) {
    this.usage = usage;
    this.info = immutableCopyOf(info);
    this.versionNamePrefix = versionNamePrefix;
    this.hasAccount = hasAccount;
    this.isGoogleCn = isGoogleCn;
    this.enableInlineVm = enableInlineVm;
    this.cached = immutableCopyOf(cached);
    this.currentVersion = currentVersion;
    this.arch = arch;
  }

  private DGRequest(Builder builder) {
    this(builder.usage, builder.info, builder.versionNamePrefix, builder.hasAccount, builder.isGoogleCn, builder.enableInlineVm, builder.cached, builder.currentVersion, builder.arch);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof DGRequest)) return false;
    DGRequest o = (DGRequest) other;
    return equals(usage, o.usage)
        && equals(info, o.info)
        && equals(versionNamePrefix, o.versionNamePrefix)
        && equals(hasAccount, o.hasAccount)
        && equals(isGoogleCn, o.isGoogleCn)
        && equals(enableInlineVm, o.enableInlineVm)
        && equals(cached, o.cached)
        && equals(currentVersion, o.currentVersion)
        && equals(arch, o.arch);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = usage != null ? usage.hashCode() : 0;
      result = result * 37 + (info != null ? info.hashCode() : 1);
      result = result * 37 + (versionNamePrefix != null ? versionNamePrefix.hashCode() : 0);
      result = result * 37 + (hasAccount != null ? hasAccount.hashCode() : 0);
      result = result * 37 + (isGoogleCn != null ? isGoogleCn.hashCode() : 0);
      result = result * 37 + (enableInlineVm != null ? enableInlineVm.hashCode() : 0);
      result = result * 37 + (cached != null ? cached.hashCode() : 1);
      result = result * 37 + (currentVersion != null ? currentVersion.hashCode() : 0);
      result = result * 37 + (arch != null ? arch.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<DGRequest> {

    public DGUsage usage;
    public List<KeyValuePair> info;
    public String versionNamePrefix;
    public Boolean hasAccount;
    public Boolean isGoogleCn;
    public Boolean enableInlineVm;
    public List<ByteString> cached;
    public Integer currentVersion;
    public String arch;

    public Builder() {
    }

    public Builder(DGRequest message) {
      super(message);
      if (message == null) return;
      this.usage = message.usage;
      this.info = copyOf(message.info);
      this.versionNamePrefix = message.versionNamePrefix;
      this.hasAccount = message.hasAccount;
      this.isGoogleCn = message.isGoogleCn;
      this.enableInlineVm = message.enableInlineVm;
      this.cached = copyOf(message.cached);
      this.currentVersion = message.currentVersion;
      this.arch = message.arch;
    }

    public Builder usage(DGUsage usage) {
      this.usage = usage;
      return this;
    }

    public Builder info(List<KeyValuePair> info) {
      this.info = checkForNulls(info);
      return this;
    }

    public Builder versionNamePrefix(String versionNamePrefix) {
      this.versionNamePrefix = versionNamePrefix;
      return this;
    }

    public Builder hasAccount(Boolean hasAccount) {
      this.hasAccount = hasAccount;
      return this;
    }

    public Builder isGoogleCn(Boolean isGoogleCn) {
      this.isGoogleCn = isGoogleCn;
      return this;
    }

    public Builder enableInlineVm(Boolean enableInlineVm) {
      this.enableInlineVm = enableInlineVm;
      return this;
    }

    public Builder cached(List<ByteString> cached) {
      this.cached = checkForNulls(cached);
      return this;
    }

    public Builder currentVersion(Integer currentVersion) {
      this.currentVersion = currentVersion;
      return this;
    }

    public Builder arch(String arch) {
      this.arch = arch;
      return this;
    }

    @Override
    public DGRequest build() {
      return new DGRequest(this);
    }
  }
}
