// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: protos-repo/droidguard.proto
package org.microg.gms.droidguard;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import okio.ByteString;

import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;

public final class DGResponse extends Message {

  public static final ByteString DEFAULT_BYTECODE = ByteString.EMPTY;
  public static final String DEFAULT_VMURL = "";
  public static final ByteString DEFAULT_VMCHECKSUM = ByteString.EMPTY;
  public static final Integer DEFAULT_EXPIRYTIMESECS = 0;
  public static final ByteString DEFAULT_CONTENT = ByteString.EMPTY;

  @ProtoField(tag = 1, type = BYTES)
  public final ByteString byteCode;

  @ProtoField(tag = 2, type = STRING)
  public final String vmUrl;

  @ProtoField(tag = 3, type = BYTES)
  public final ByteString vmChecksum;

  @ProtoField(tag = 4, type = INT32)
  public final Integer expiryTimeSecs;

  @ProtoField(tag = 5, type = BYTES)
  public final ByteString content;

  public DGResponse(ByteString byteCode, String vmUrl, ByteString vmChecksum, Integer expiryTimeSecs, ByteString content) {
    this.byteCode = byteCode;
    this.vmUrl = vmUrl;
    this.vmChecksum = vmChecksum;
    this.expiryTimeSecs = expiryTimeSecs;
    this.content = content;
  }

  private DGResponse(Builder builder) {
    this(builder.byteCode, builder.vmUrl, builder.vmChecksum, builder.expiryTimeSecs, builder.content);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof DGResponse)) return false;
    DGResponse o = (DGResponse) other;
    return equals(byteCode, o.byteCode)
        && equals(vmUrl, o.vmUrl)
        && equals(vmChecksum, o.vmChecksum)
        && equals(expiryTimeSecs, o.expiryTimeSecs)
        && equals(content, o.content);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = byteCode != null ? byteCode.hashCode() : 0;
      result = result * 37 + (vmUrl != null ? vmUrl.hashCode() : 0);
      result = result * 37 + (vmChecksum != null ? vmChecksum.hashCode() : 0);
      result = result * 37 + (expiryTimeSecs != null ? expiryTimeSecs.hashCode() : 0);
      result = result * 37 + (content != null ? content.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<DGResponse> {

    public ByteString byteCode;
    public String vmUrl;
    public ByteString vmChecksum;
    public Integer expiryTimeSecs;
    public ByteString content;

    public Builder() {
    }

    public Builder(DGResponse message) {
      super(message);
      if (message == null) return;
      this.byteCode = message.byteCode;
      this.vmUrl = message.vmUrl;
      this.vmChecksum = message.vmChecksum;
      this.expiryTimeSecs = message.expiryTimeSecs;
      this.content = message.content;
    }

    public Builder byteCode(ByteString byteCode) {
      this.byteCode = byteCode;
      return this;
    }

    public Builder vmUrl(String vmUrl) {
      this.vmUrl = vmUrl;
      return this;
    }

    public Builder vmChecksum(ByteString vmChecksum) {
      this.vmChecksum = vmChecksum;
      return this;
    }

    public Builder expiryTimeSecs(Integer expiryTimeSecs) {
      this.expiryTimeSecs = expiryTimeSecs;
      return this;
    }

    public Builder content(ByteString content) {
      this.content = content;
      return this;
    }

    @Override
    public DGResponse build() {
      return new DGResponse(this);
    }
  }
}
