// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: protos-repo/droidguard.proto
package org.microg.gms.droidguard;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class DGUsage extends Message {

  public static final String DEFAULT_TYPE = "";
  public static final String DEFAULT_PACKAGENAME = "";

  @ProtoField(tag = 1, type = STRING)
  public final String type;

  @ProtoField(tag = 2, type = STRING)
  public final String packageName;

  public DGUsage(String type, String packageName) {
    this.type = type;
    this.packageName = packageName;
  }

  private DGUsage(Builder builder) {
    this(builder.type, builder.packageName);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof DGUsage)) return false;
    DGUsage o = (DGUsage) other;
    return equals(type, o.type)
        && equals(packageName, o.packageName);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = type != null ? type.hashCode() : 0;
      result = result * 37 + (packageName != null ? packageName.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<DGUsage> {

    public String type;
    public String packageName;

    public Builder() {
    }

    public Builder(DGUsage message) {
      super(message);
      if (message == null) return;
      this.type = message.type;
      this.packageName = message.packageName;
    }

    public Builder type(String type) {
      this.type = type;
      return this;
    }

    public Builder packageName(String packageName) {
      this.packageName = packageName;
      return this;
    }

    @Override
    public DGUsage build() {
      return new DGUsage(this);
    }
  }
}
