// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: protos-repo/droidguard.proto
package org.microg.gms.droidguard;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class KeyValuePair extends Message {

  public static final String DEFAULT_KEY = "";
  public static final String DEFAULT_VAL = "";

  @ProtoField(tag = 1, type = STRING)
  public final String key;

  @ProtoField(tag = 2, type = STRING)
  public final String val;

  public KeyValuePair(String key, String val) {
    this.key = key;
    this.val = val;
  }

  private KeyValuePair(Builder builder) {
    this(builder.key, builder.val);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof KeyValuePair)) return false;
    KeyValuePair o = (KeyValuePair) other;
    return equals(key, o.key)
        && equals(val, o.val);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = key != null ? key.hashCode() : 0;
      result = result * 37 + (val != null ? val.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<KeyValuePair> {

    public String key;
    public String val;

    public Builder() {
    }

    public Builder(KeyValuePair message) {
      super(message);
      if (message == null) return;
      this.key = message.key;
      this.val = message.val;
    }

    public Builder key(String key) {
      this.key = key;
      return this;
    }

    public Builder val(String val) {
      this.val = val;
      return this;
    }

    @Override
    public KeyValuePair build() {
      return new KeyValuePair(this);
    }
  }
}
